INSERT INTO legal_app_lawsectiondetail
(simplified_explanation, offence_description, imprisonment_term, fine_amount, compensation, bailable_status, cognizable_status, example_scenario, last_updated, section_id)
VALUES

('Explains punishment for murder in simple terms.',
'Intentional killing of a person.',
'Death penalty or life imprisonment',
'Fine as decided by court',
'Compensation to victim family',
'Non-bailable',
'Cognizable',
'Example: A person intentionally kills another.',
CURRENT_TIMESTAMP, 65),

('Explains attempt to murder.',
'Attempt to kill but victim survives.',
'Up to 10 years or life imprisonment',
'Fine may apply',
'Compensation possible',
'Non-bailable',
'Cognizable',
'Example: Attacking someone with intent to kill.',
CURRENT_TIMESTAMP, 66),

('Defines theft clearly.',
'Taking property without permission.',
'Up to 3 years imprisonment',
'Fine or both',
'Compensation possible',
'Bailable',
'Cognizable',
'Example: Stealing a mobile phone.',
CURRENT_TIMESTAMP, 67),

('Explains arrest without warrant.',
'Police arrest without court approval.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Cognizable',
'Example: Arrest in serious crime.',
CURRENT_TIMESTAMP, 68),

('Explains police arrest powers.',
'Authority to arrest individuals.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Cognizable',
'Example: Arrest during investigation.',
CURRENT_TIMESTAMP, 69),

('Explains arrest procedure.',
'Steps police must follow.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Cognizable',
'Example: Informing reason of arrest.',
CURRENT_TIMESTAMP, 70),

('Explains police report.',
'Submission after investigation.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Filing charge sheet.',
CURRENT_TIMESTAMP, 71),

('Explains framing of charges.',
'Court defines charges.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Court decides charges.',
CURRENT_TIMESTAMP, 72),

('Defines legal terms.',
'Basic definitions in law.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Definition of evidence.',
CURRENT_TIMESTAMP, 73),

('Explains invalid confession.',
'Confession under threat.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Forced confession.',
CURRENT_TIMESTAMP, 74),

('Explains electronic evidence.',
'Use of digital records.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Email proof in court.',
CURRENT_TIMESTAMP, 75),

('Explains drug prohibition.',
'Illegal drug handling.',
'Up to 10+ years',
'Heavy fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Selling drugs.',
CURRENT_TIMESTAMP, 76),

('Explains drug possession punishment.',
'Possession of illegal drugs.',
'Varies by quantity',
'Heavy fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Carrying drugs.',
CURRENT_TIMESTAMP, 77),

('Explains drug consumption punishment.',
'Using illegal drugs.',
'Up to 1 year',
'Fine',
'Not applicable',
'Bailable',
'Cognizable',
'Example: Drug use case.',
CURRENT_TIMESTAMP, 78),

('Explains firearm license rules.',
'Illegal possession of arms.',
'Up to 3 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Keeping gun without license.',
CURRENT_TIMESTAMP, 79),

('Explains prohibited weapons.',
'Possession of restricted arms.',
'Up to 7 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Owning banned weapons.',
CURRENT_TIMESTAMP, 80),

('Explains punishment for arms offences.',
'Illegal use of weapons.',
'Up to 7 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Using illegal firearm.',
CURRENT_TIMESTAMP, 81),

('Explains equality before law.',
'Equal treatment under law.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Equal rights for citizens.',
CURRENT_TIMESTAMP, 82),

('Explains freedom of speech.',
'Right to express opinions.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Speaking freely.',
CURRENT_TIMESTAMP, 83),

('Explains right to life.',
'Protection of life and liberty.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Right to live with dignity.',
CURRENT_TIMESTAMP, 84),

('Explains election disqualification.',
'Disqualification due to criminal conviction.',
'Varies by offence',
'Fine may apply',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Candidate disqualified after conviction.',
CURRENT_TIMESTAMP, 85),

('Explains corrupt practices in elections.',
'Use of bribery or undue influence.',
'Up to 3 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Offering money for votes.',
CURRENT_TIMESTAMP, 86),

('Explains invalid election conditions.',
'Election declared void.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Election cancelled due to fraud.',
CURRENT_TIMESTAMP, 87),

('Explains citizenship by birth.',
'Acquiring citizenship by birth.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Born in India.',
CURRENT_TIMESTAMP, 88),

('Explains citizenship by registration.',
'Citizenship through application.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Applying for citizenship.',
CURRENT_TIMESTAMP, 89),

('Explains termination of citizenship.',
'Loss of citizenship rights.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Voluntary renunciation.',
CURRENT_TIMESTAMP, 90),

('Explains preventive detention.',
'Detention for national security.',
'Up to prescribed period',
'Not applicable',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Detaining suspected threat.',
CURRENT_TIMESTAMP, 91),

('Explains communication of detention grounds.',
'Informing detainee of reasons.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Informing arrested person.',
CURRENT_TIMESTAMP, 92),

('Explains advisory board review.',
'Review of detention orders.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Review by authority.',
CURRENT_TIMESTAMP, 93),

('Explains espionage offence.',
'Spying against the state.',
'Up to 14 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Sharing secret documents.',
CURRENT_TIMESTAMP, 94),

('Explains unauthorized disclosure.',
'Leak of confidential data.',
'Up to 3 years',
'Fine',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Leaking government files.',
CURRENT_TIMESTAMP, 95),

('Explains protection of official secrets.',
'Handling classified data.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Securing sensitive info.',
CURRENT_TIMESTAMP, 96),

('Explains right to information.',
'Access government data.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Filing RTI request.',
CURRENT_TIMESTAMP, 97),

('Explains RTI application process.',
'Procedure to request info.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Submitting RTI form.',
CURRENT_TIMESTAMP, 98),

('Explains RTI exemptions.',
'Restricted information.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: National security data.',
CURRENT_TIMESTAMP, 99),

('Explains tribunal jurisdiction.',
'Scope of tribunal authority.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Service disputes.',
CURRENT_TIMESTAMP, 100),

('Explains filing application in tribunal.',
'Procedure to file case.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Filing service complaint.',
CURRENT_TIMESTAMP, 101),

('Explains tribunal procedures.',
'Process followed in tribunal.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Tribunal hearing.',
CURRENT_TIMESTAMP, 102),

('Explains Lokpal establishment.',
'Anti-corruption authority.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Complaint against official.',
CURRENT_TIMESTAMP, 103),

('Explains inquiry against officials.',
'Investigation of corruption.',
'Varies',
'Fine may apply',
'Not applicable',
'Non-bailable',
'Cognizable',
'Example: Corruption case.',
CURRENT_TIMESTAMP, 104),

('Explains action after corruption inquiry.',
'Steps taken after investigation.',
'Varies by offence',
'Fine may apply',
'Compensation possible',
'Non-bailable',
'Cognizable',
'Example: Prosecution after corruption inquiry.',
CURRENT_TIMESTAMP, 105),

('Explains functions of vigilance commission.',
'Monitoring corruption in institutions.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Investigating complaints.',
CURRENT_TIMESTAMP, 106),

('Explains jurisdiction of vigilance authority.',
'Scope of investigation powers.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Handling corruption cases.',
CURRENT_TIMESTAMP, 107),

('Explains vigilance inquiry process.',
'Procedure for inquiry.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Inquiry into misconduct.',
CURRENT_TIMESTAMP, 108),

('Explains eviction notice.',
'Notice to unauthorized occupant.',
'Not applicable',
'Fine may apply',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Notice to vacate property.',
CURRENT_TIMESTAMP, 109),

('Explains eviction process.',
'Removal from public premises.',
'Not applicable',
'Fine may apply',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Government eviction.',
CURRENT_TIMESTAMP, 110),

('Explains recovery of dues.',
'Recovery of unpaid rent or damages.',
'Not applicable',
'Fine applicable',
'Compensation possible',
'Not applicable',
'Not applicable',
'Example: Recovering dues.',
CURRENT_TIMESTAMP, 111),

('Explains conditions for marriage.',
'Legal conditions for valid marriage.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Minimum age requirement.',
CURRENT_TIMESTAMP, 112),

('Explains divorce provisions.',
'Grounds for dissolution.',
'Not applicable',
'Not applicable',
'Compensation possible',
'Not applicable',
'Not applicable',
'Example: Divorce due to cruelty.',
CURRENT_TIMESTAMP, 113),

('Explains maintenance during proceedings.',
'Financial support to spouse.',
'Not applicable',
'Not applicable',
'Compensation applicable',
'Not applicable',
'Not applicable',
'Example: Monthly maintenance.',
CURRENT_TIMESTAMP, 114),

('Explains civil marriage conditions.',
'Conditions under special marriage.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Inter-religion marriage.',
CURRENT_TIMESTAMP, 115),

('Explains marriage registration.',
'Registration of marriage.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Registering marriage legally.',
CURRENT_TIMESTAMP, 116),

('Explains divorce under special law.',
'Legal divorce process.',
'Not applicable',
'Not applicable',
'Compensation possible',
'Not applicable',
'Not applicable',
'Example: Court granted divorce.',
CURRENT_TIMESTAMP, 117),

('Explains inheritance rights.',
'Rights in ancestral property.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Property division.',
CURRENT_TIMESTAMP, 118),

('Explains succession rules.',
'General inheritance rules.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Legal heirs.',
CURRENT_TIMESTAMP, 119),

('Explains female property rights.',
'Property rights of women.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Daughter inheritance.',
CURRENT_TIMESTAMP, 120),

('Explains guardian appointment.',
'Appointment of guardian.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Court appoints guardian.',
CURRENT_TIMESTAMP, 121),

('Explains welfare of minor.',
'Minor’s best interest.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Child custody case.',
CURRENT_TIMESTAMP, 122),

('Explains custody rights.',
'Custody of minor.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Custody decision.',
CURRENT_TIMESTAMP, 123),

('Explains domestic violence definition.',
'Physical or emotional abuse.',
'Up to prescribed term',
'Fine',
'Compensation to victim',
'Non-bailable',
'Cognizable',
'Example: Abuse within family.',
CURRENT_TIMESTAMP, 124), 

('Explains filing of domestic violence complaint.',
'Victim can file complaint before magistrate.',
'Not applicable',
'Not applicable',
'Compensation possible',
'Not applicable',
'Not applicable',
'Example: Filing DV complaint in court.',
CURRENT_TIMESTAMP, 125),

('Explains protection orders.',
'Court may issue protection orders.',
'Not applicable',
'Not applicable',
'Compensation possible',
'Not applicable',
'Not applicable',
'Example: Court restrains abuser.',
CURRENT_TIMESTAMP, 126),

('Explains sale of property.',
'Transfer of ownership for price.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Buying a house.',
CURRENT_TIMESTAMP, 127),

('Explains lease of property.',
'Right to use property for time.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Renting property.',
CURRENT_TIMESTAMP, 128),

('Explains gift transfer.',
'Property given without consideration.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Gifting land.',
CURRENT_TIMESTAMP, 129),

('Explains compulsory registration.',
'Certain documents must be registered.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Registering sale deed.',
CURRENT_TIMESTAMP, 130),

('Explains document presentation.',
'Documents must be presented for registration.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Submitting property document.',
CURRENT_TIMESTAMP, 131),

('Explains effect of non-registration.',
'Unregistered documents not valid.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Invalid sale without registration.',
CURRENT_TIMESTAMP, 132),

('Explains easement rights.',
'Right to use another property.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Right of way.',
CURRENT_TIMESTAMP, 133),

('Explains acquisition of easement.',
'How easement is acquired.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Long-term usage rights.',
CURRENT_TIMESTAMP, 134),

('Explains easement by prescription.',
'Right gained by continuous use.',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Not applicable',
'Example: Using pathway for years.',
CURRENT_TIMESTAMP, 135),

-- 136–140
('Explains benami property prohibition.','Holding property in another name illegally.','Up to 7 years','Fine','Property confiscation','Non-bailable','Cognizable','Example: Buying property in another name to hide ownership.',CURRENT_TIMESTAMP,136),
('Explains confiscation under benami law.','Illegal property seized by authority.','Not applicable','Not applicable','Property confiscated','Not applicable','Not applicable','Example: Government seizes benami land.',CURRENT_TIMESTAMP,137),
('Explains penalties under benami law.','Punishment for benami transactions.','Up to 7 years','Fine','Not applicable','Non-bailable','Cognizable','Example: Acting as benamidar.',CURRENT_TIMESTAMP,138),
('Explains RERA registration.','Real estate projects must be registered.','Not applicable','Fine','Compensation possible','Not applicable','Not applicable','Example: Builder registers project.',CURRENT_TIMESTAMP,139),
('Explains promoter duties.','Responsibilities of real estate promoters.','Not applicable','Fine','Compensation','Not applicable','Not applicable','Example: Delay in construction.',CURRENT_TIMESTAMP,140),

-- 141–145
('Explains compensation in real estate.','Buyer can claim compensation.','Not applicable','Not applicable','Compensation applicable','Not applicable','Not applicable','Example: Delay in possession.',CURRENT_TIMESTAMP,141),
('Explains valid contracts.','Requirements for valid agreement.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Agreement with consent.',CURRENT_TIMESTAMP,142),
('Explains breach of contract.','Failure to perform contract.','Not applicable','Damages','Compensation','Not applicable','Not applicable','Example: Not delivering goods.',CURRENT_TIMESTAMP,143),
('Explains indemnity contract.','Protection against loss.','Not applicable','Not applicable','Compensation applicable','Not applicable','Not applicable','Example: Insurance contract.',CURRENT_TIMESTAMP,144),
('Explains specific performance.','Court enforces contract.','Not applicable','Not applicable','Compensation possible','Not applicable','Not applicable','Example: Court orders completion.',CURRENT_TIMESTAMP,145),

-- 146–150
('Explains declaratory relief.','Court declares rights.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Ownership declaration.',CURRENT_TIMESTAMP,146),
('Explains injunction.','Court orders to stop act.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Stop illegal construction.',CURRENT_TIMESTAMP,147),
('Explains sale of goods.','Transfer of goods for price.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Selling product.',CURRENT_TIMESTAMP,148),
('Explains implied conditions.','Conditions assumed in sale.','Not applicable','Not applicable','Compensation possible','Not applicable','Not applicable','Example: Quality of goods.',CURRENT_TIMESTAMP,149),
('Explains buyer remedies.','Rights of buyer.','Not applicable','Damages','Compensation','Not applicable','Not applicable','Example: Defective goods.',CURRENT_TIMESTAMP,150),

-- 151–155
('Explains partnership definition.','Agreement to share profits.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Business partnership.',CURRENT_TIMESTAMP,151),
('Explains duties of partners.','Responsibilities of partners.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Acting in good faith.',CURRENT_TIMESTAMP,152),
('Explains dissolution of firm.','Ending partnership.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Business closure.',CURRENT_TIMESTAMP,153),
('Explains cheque definition.','Negotiable instrument.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Bank cheque.',CURRENT_TIMESTAMP,154),
('Explains presumptions in NI Act.','Legal presumptions.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Presumption of debt.',CURRENT_TIMESTAMP,155),

-- 156–160
('Explains cheque bounce offence.','Dishonour of cheque.','Up to 2 years','Fine','Compensation','Bailable','Non-cognizable','Example: Cheque bounce case.',CURRENT_TIMESTAMP,156),
('Explains IT Act damage.','Damage to computer systems.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Hacking system.',CURRENT_TIMESTAMP,157),
('Explains hacking offence.','Unauthorized access.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Accessing system illegally.',CURRENT_TIMESTAMP,158),
('Explains breach of confidentiality.','Unauthorized disclosure.','Up to 2 years','Fine','Not applicable','Bailable','Non-cognizable','Example: Sharing private data.',CURRENT_TIMESTAMP,159),
('Explains data processing rules.','Handling personal data.','Not applicable','Fine','Compensation','Not applicable','Not applicable','Example: Storing user data.',CURRENT_TIMESTAMP,160),

-- 161–165
('Explains data rights.','Rights of individuals.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Right to access data.',CURRENT_TIMESTAMP,161),
('Explains penalties under data law.','Violation penalties.','Not applicable','Heavy fine','Compensation','Not applicable','Not applicable','Example: Data breach fine.',CURRENT_TIMESTAMP,162),
('Explains intermediary duties.','Responsibilities of platforms.','Not applicable','Fine','Not applicable','Not applicable','Not applicable','Example: Social media rules.',CURRENT_TIMESTAMP,163),
('Explains grievance redressal.','Handling complaints.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Reporting abuse.',CURRENT_TIMESTAMP,164),
('Explains compliance rules.','Following legal requirements.','Not applicable','Fine','Not applicable','Not applicable','Not applicable','Example: Platform compliance.',CURRENT_TIMESTAMP,165),

-- 166–170
('Explains cyber incident reporting.','Reporting cyber attacks.','Not applicable','Fine','Not applicable','Not applicable','Not applicable','Example: Reporting breach.',CURRENT_TIMESTAMP,166),
('Explains cyber monitoring.','Monitoring threats.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Security checks.',CURRENT_TIMESTAMP,167),
('Explains coordination in cyber law.','Coordination with agencies.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: CERT cooperation.',CURRENT_TIMESTAMP,168),
('Explains impersonation offence.','Cheating by impersonation.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Fake identity scam.',CURRENT_TIMESTAMP,169),
('Explains cheating offence.','Dishonest inducement.','Up to 7 years','Fine','Compensation','Non-bailable','Cognizable','Example: Fraud case.',CURRENT_TIMESTAMP,170),

-- 171–175
('Explains forgery offence.','Forgery for cheating.','Up to 7 years','Fine','Compensation','Non-bailable','Cognizable','Example: Fake documents.',CURRENT_TIMESTAMP,171),
('Explains patent definitions.','Definitions in patent law.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Patent term.',CURRENT_TIMESTAMP,172),
('Explains non-patentable inventions.','What cannot be patented.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Abstract ideas.',CURRENT_TIMESTAMP,173),
('Explains patent rights.','Rights of patent holder.','Not applicable','Not applicable','Compensation','Not applicable','Not applicable','Example: Exclusive use.',CURRENT_TIMESTAMP,174),
('Explains copyright works.','Protected works.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Books and music.',CURRENT_TIMESTAMP,175),

-- 176–180
('Explains copyright rights.','Rights of owner.','Not applicable','Not applicable','Compensation','Not applicable','Not applicable','Example: Copy restriction.',CURRENT_TIMESTAMP,176),
('Explains copyright infringement.','Unauthorized use.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Pirated movie.',CURRENT_TIMESTAMP,177),
('Explains trademark definitions.','Trademark basics.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Brand logo.',CURRENT_TIMESTAMP,178),
('Explains trademark refusal.','Grounds for rejection.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Generic name.',CURRENT_TIMESTAMP,179),
('Explains trademark infringement.','Unauthorized usage.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Fake brand.',CURRENT_TIMESTAMP,180),

-- 181–185
('Explains design definitions.','Design law basics.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Product design.',CURRENT_TIMESTAMP,181),
('Explains design registration.','Registering design.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Industrial design.',CURRENT_TIMESTAMP,182),
('Explains design piracy.','Copying design illegally.','Up to 2 years','Fine','Compensation','Bailable','Cognizable','Example: Copying product.',CURRENT_TIMESTAMP,183),
('Explains GI definitions.','Geographical indication basics.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Darjeeling tea.',CURRENT_TIMESTAMP,184),
('Explains GI registration.','Registering GI.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Regional product.',CURRENT_TIMESTAMP,185),

-- 186–190
('Explains GI infringement.','Unauthorized GI use.','Up to 3 years','Fine','Compensation','Bailable','Cognizable','Example: Fake GI product.',CURRENT_TIMESTAMP,186),
('Explains consumer definitions.','Consumer law basics.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Buyer rights.',CURRENT_TIMESTAMP,187),
('Explains complaint filing.','Consumer complaint process.','Not applicable','Not applicable','Compensation','Not applicable','Not applicable','Example: Filing case.',CURRENT_TIMESTAMP,188),
('Explains consumer procedure.','Case procedure.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Court hearing.',CURRENT_TIMESTAMP,189),
('Explains legal metrology definitions.','Standards of measurement.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Weights and measures.',CURRENT_TIMESTAMP,190),

-- 191–195
('Explains verification rules.','Checking standards.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Product testing.',CURRENT_TIMESTAMP,191),
('Explains metrology penalties.','Violation penalties.','Fine','Fine','Not applicable','Not applicable','Not applicable','Example: Wrong weight.',CURRENT_TIMESTAMP,192),
('Explains food safety definitions.','Food safety basics.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Safe food.',CURRENT_TIMESTAMP,193),
('Explains food business responsibility.','Duties of food operators.','Not applicable','Fine','Compensation','Not applicable','Not applicable','Example: Hygiene rules.',CURRENT_TIMESTAMP,194),
('Explains unsafe food punishment.','Penalty for unsafe food.','Up to 6 years','Fine','Compensation','Non-bailable','Cognizable','Example: Selling unsafe food.',CURRENT_TIMESTAMP,195),

-- 196–199
('Explains BIS functions.','Functions of standards body.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: Quality control.',CURRENT_TIMESTAMP,196),
('Explains certification rules.','Certification process.','Not applicable','Not applicable','Not applicable','Not applicable','Not applicable','Example: ISI mark.',CURRENT_TIMESTAMP,197),
('Explains BIS penalties.','Penalty for violation.','Fine','Fine','Not applicable','Not applicable','Not applicable','Example: Fake certification.',CURRENT_TIMESTAMP,198),
('Explains drug sale prohibition.','Illegal sale of drugs.','Up to 5 years','Fine','Compensation','Non-bailable','Cognizable','Example: Selling banned drugs.',CURRENT_TIMESTAMP,199);