# Generated by Django 5.2.4 on 2026-02-22 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company'), ('civil', 'Civil Law')], max_length=30)),
                ('statute_name', models.CharField(blank=True, max_length=255)),
                ('section_reference', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(help_text='Short structured summary')),
                ('full_text', models.TextField(blank=True)),
                ('penalties', models.TextField(blank=True, help_text='Penalties/punishments applicable, free text')),
                ('related_sections', models.CharField(blank=True, help_text='Comma separated section codes', max_length=300)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LawInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('section_code', models.CharField(blank=True, max_length=50)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True, default='')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='legal_app.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('complainant_name', models.CharField(blank=True, max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('relief_sought', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LawList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='law_lists', to='legal_app.lawdetail')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('lawyer_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(blank=True, help_text='Comma separated list', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('lawyer_review', 'Lawyer Review'), ('platform', 'Platform Feedback'), ('assistant', 'AI Assistant Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Inquiry')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating 1-5')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True, help_text='Textual description of evidence provided')),
                ('relief_sought', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('law_references', models.ManyToManyField(blank=True, related_name='complaints', to='legal_app.lawdetail')),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_lawyer', to='legal_app.lawyer'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('case_type', models.CharField(max_length=100)),
                ('lawyer_type', models.CharField(help_text='Type of lawyer/specialization needed', max_length=120)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('client', 'lawyer')},
        ),
    ]
