# Generated by Django 5.2.4 on 2026-03-07 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='LawDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'domain_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True, default='')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='legal_app.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('complainant_name', models.CharField(blank=True, max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('relief_sought', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_title', models.CharField(max_length=300)),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('enactment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('law_type', models.CharField(blank=True, max_length=100)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='legal_app.lawcategory')),
            ],
            options={
                'ordering': ['law_title'],
            },
        ),
        migrations.AddField(
            model_name='lawcategory',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='legal_app.lawdomain'),
        ),
        migrations.CreateModel(
            name='LawSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('section_title', models.CharField(max_length=300)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('section_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal_app.law')),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='LawSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified_explanation', models.TextField(blank=True)),
                ('offence_description', models.TextField(blank=True)),
                ('imprisonment_term', models.CharField(blank=True, max_length=300)),
                ('fine_amount', models.CharField(blank=True, max_length=300)),
                ('compensation', models.TextField(blank=True)),
                ('bailable_status', models.CharField(blank=True, max_length=50)),
                ('cognizable_status', models.CharField(blank=True, max_length=50)),
                ('example_scenario', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='legal_app.lawsection')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('lawyer_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(blank=True, help_text='Comma separated list', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyer_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('lawyer_review', 'Lawyer Review'), ('platform', 'Platform Feedback'), ('assistant', 'AI Assistant Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Inquiry')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating 1-5')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True, help_text='Textual description of evidence provided')),
                ('relief_sought', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('law_references', models.ManyToManyField(blank=True, related_name='complaints', to='legal_app.lawsection')),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_lawyer', to='legal_app.lawyer'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('case_type', models.CharField(max_length=100)),
                ('lawyer_type', models.CharField(help_text='Type of lawyer/specialization needed', max_length=120)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='legal_app.lawyer')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('feedback', 'Feedback'), ('chat', 'Chat'), ('system', 'System'), ('verification', 'Verification'), ('reminder', 'Reminder')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='Optional ID of related object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('client', 'lawyer')},
        ),
    ]
