# Generated by Django 5.2.4 on 2025-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('section_code', models.CharField(blank=True, max_length=50)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
    ]
