# Generated by Django 5.2.4 on 2026-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], db_index=True, default='pending', max_length=10),
        ),
    ]
