# Generated by Django 5.2.4 on 2025-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('consultation_fee', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
