# Generated by Django 5.2.4 on 2026-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0002_chatroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_photos/'),
        ),
    ]
