# Generated by GitHub Copilot on 2026-05-03

from django.db import migrations, models


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table_name)
            return any(getattr(col, 'name', None) == column_name for col in description)
        except Exception:
            cursor.execute(f"PRAGMA table_info({table_name})")
            return any(row[1] == column_name for row in cursor.fetchall())


def add_missing_columns(apps, schema_editor):
    Complaint = apps.get_model('legal_app', 'Complaint')
    ComplaintDraft = apps.get_model('legal_app', 'ComplaintDraft')

    def add_column(table: str, column: str, sql_type: str):
        if _column_exists(schema_editor, table, column):
            return
        qn = schema_editor.quote_name
        schema_editor.execute(f"ALTER TABLE {qn(table)} ADD COLUMN {qn(column)} {sql_type}")

    # Use NOT NULL DEFAULT '' to satisfy existing NOT NULL constraints patterns.
    add_column(Complaint._meta.db_table, 'respondent_phone', "varchar(20) NOT NULL DEFAULT ''")
    add_column(ComplaintDraft._meta.db_table, 'respondent_phone', "varchar(20) NOT NULL DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0003_complaint_police_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='complaint',
                    name='respondent_phone',
                    field=models.CharField(blank=True, default='', max_length=20),
                ),
                migrations.AddField(
                    model_name='complaintdraft',
                    name='respondent_phone',
                    field=models.CharField(blank=True, default='', max_length=20),
                ),
            ],
        ),
    ]
