# Generated by Django 5.2.4 on 2025-09-25 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0004_remove_client_password_remove_lawyer_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company')], max_length=30)),
                ('statute_name', models.CharField(blank=True, max_length=255)),
                ('section_reference', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(help_text='Short structured summary')),
                ('full_text', models.TextField(blank=True)),
                ('related_sections', models.CharField(blank=True, help_text='Comma separated section codes', max_length=300)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True, help_text='Textual description of evidence provided')),
                ('relief_sought', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='legal_app.lawyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('law_references', models.ManyToManyField(blank=True, related_name='complaints', to='legal_app.lawdetail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
