# Generated by Django 5.2.4 on 2025-09-25 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0005_lawdetail_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('complainant_name', models.CharField(blank=True, max_length=200)),
                ('complainant_phone', models.CharField(blank=True, max_length=20)),
                ('complainant_email', models.EmailField(blank=True, max_length=254)),
                ('complainant_address', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_address', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('damages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('relief_sought', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
