# Generated by Django 5.2.4 on 2025-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0006_complaintdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated list', max_length=200),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
