# Generated by Django 5.2.4 on 2025-10-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0011_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LawyerReview',
        ),
    ]
