# Generated by Django 5.2.4 on 2025-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0012_delete_lawyerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='law_lists', to='legal_app.lawdetail')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
