# Generated by Django 5.2.4 on 2025-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0013_lawlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawdetail',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer Protection'), ('ipc', 'Criminal / IPC'), ('labour', 'Labour / Employment'), ('family', 'Family / Domestic'), ('cyber', 'Cyber Crime'), ('property', 'Property / Tenancy'), ('corporate', 'Corporate / Company'), ('civil', 'Civil Law')], max_length=30),
        ),
    ]
