# Generated by Django 5.2.4 on 2025-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0014_alter_lawdetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdetail',
            name='penalties',
            field=models.TextField(blank=True, help_text='Penalties/punishments applicable, free text'),
        ),
    ]
